package AutoDanfeCadTransp;

import javax.swing.plaf.basic.BasicInternalFrameUI;


public class CadastroTransportadoras extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroTransportadoras
     */
    public CadastroTransportadoras() {
        initComponents();
       
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfRazaoSocialTransp = new test.RoundedTextField();
        tfCNPJ = new test.RoundedTextField();
        tfLogradouroTransp = new test.RoundedTextField();
        tfMunicipio = new test.RoundedTextField();
        tfInscricaoEstadual = new test.RoundedTextField();
        tfUF = new test.RoundedTextField();
        btnAdicionarTransp = new Components.btnRounded();
        btnRemoverTransp = new Components.btnRounded();
        btnAtualizarTransp = new Components.btnRounded();

        setMinimumSize(new java.awt.Dimension(1000, 596));

        jPanel1.setBackground(new java.awt.Color(223, 223, 223));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cadastro de Transportadoras");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        tfRazaoSocialTransp.setBackground(new java.awt.Color(255, 255, 255));
        tfRazaoSocialTransp.setText("Razão Social");
        tfRazaoSocialTransp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfRazaoSocialTranspFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfRazaoSocialTranspFocusLost(evt);
            }
        });

        tfCNPJ.setText("CNPJ");

        tfLogradouroTransp.setText("Logradouro");
        tfLogradouroTransp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfLogradouroTranspFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfLogradouroTranspFocusLost(evt);
            }
        });

        tfMunicipio.setText("Município");

        tfInscricaoEstadual.setText("Inscrição Estadual");

        tfUF.setText("UF");

        btnAdicionarTransp.setBackground(new java.awt.Color(0, 153, 153));
        btnAdicionarTransp.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionarTransp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/adicionarLogo.png"))); // NOI18N
        btnAdicionarTransp.setText("Adicionar");
        btnAdicionarTransp.setBorderColor(new java.awt.Color(0, 153, 153));
        btnAdicionarTransp.setColor(new java.awt.Color(0, 153, 153));
        btnAdicionarTransp.setColorClick(new java.awt.Color(0, 134, 134));
        btnAdicionarTransp.setColorOver(new java.awt.Color(0, 114, 114));

        btnRemoverTransp.setBackground(new java.awt.Color(153, 0, 0));
        btnRemoverTransp.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoverTransp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancelarLogo.png"))); // NOI18N
        btnRemoverTransp.setText("Remover");
        btnRemoverTransp.setBorderColor(new java.awt.Color(153, 0, 0));
        btnRemoverTransp.setColor(new java.awt.Color(153, 0, 0));
        btnRemoverTransp.setColorClick(new java.awt.Color(175, 0, 0));
        btnRemoverTransp.setColorOver(new java.awt.Color(154, 0, 0));

        btnAtualizarTransp.setBackground(new java.awt.Color(191, 189, 189));
        btnAtualizarTransp.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizarTransp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/atualizarLogo.png"))); // NOI18N
        btnAtualizarTransp.setText("Atualizar");
        btnAtualizarTransp.setBorderColor(new java.awt.Color(191, 189, 189));
        btnAtualizarTransp.setColor(new java.awt.Color(191, 189, 189));
        btnAtualizarTransp.setColorClick(new java.awt.Color(159, 159, 159));
        btnAtualizarTransp.setColorOver(new java.awt.Color(180, 180, 180));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtualizarTransp, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnRemoverTransp, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnAdicionarTransp, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfLogradouroTransp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfRazaoSocialTransp, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfInscricaoEstadual, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                            .addComponent(tfUF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfRazaoSocialTransp, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(tfCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfInscricaoEstadual, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(tfLogradouroTransp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(tfUF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarTransp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoverTransp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizarTransp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfRazaoSocialTranspFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfRazaoSocialTranspFocusGained
        tfRazaoSocialTransp.setText("");
    }//GEN-LAST:event_tfRazaoSocialTranspFocusGained

    private void tfRazaoSocialTranspFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfRazaoSocialTranspFocusLost
        if (tfRazaoSocialTransp.getText().isEmpty()) {
            tfRazaoSocialTransp.setText("Razão Social");
        }
    }//GEN-LAST:event_tfRazaoSocialTranspFocusLost

    private void tfLogradouroTranspFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLogradouroTranspFocusGained
        tfLogradouroTransp.setText("");
    }//GEN-LAST:event_tfLogradouroTranspFocusGained

    private void tfLogradouroTranspFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLogradouroTranspFocusLost
        if(tfLogradouroTransp.getText().isEmpty()) {
            tfLogradouroTransp.setText("Logradouro");
        }
    }//GEN-LAST:event_tfLogradouroTranspFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.btnRounded btnAdicionarTransp;
    private Components.btnRounded btnAtualizarTransp;
    private Components.btnRounded btnRemoverTransp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private test.RoundedTextField tfCNPJ;
    private test.RoundedTextField tfInscricaoEstadual;
    private test.RoundedTextField tfLogradouroTransp;
    private test.RoundedTextField tfMunicipio;
    private test.RoundedTextField tfRazaoSocialTransp;
    private test.RoundedTextField tfUF;
    // End of variables declaration//GEN-END:variables
}
