package AutoDanfeCadTransp;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;


public class CadastroTransportadoras extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroTransportadoras
     */
    public CadastroTransportadoras() {
        initComponents();
       
        tfRazaoSocialTransp.setForeground(Color.GRAY);
        tfLogradouroTransp.setForeground(Color.GRAY);
        tfMunicipio.setForeground(Color.GRAY);
        tfCNPJ.setForeground(Color.GRAY);
        tfUF.setForeground(Color.GRAY);
        tfInscricaoEstadual.setForeground(Color.GRAY);
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfRazaoSocialTransp = new test.RoundedTextField();
        tfCNPJ = new test.RoundedTextField();
        tfLogradouroTransp = new test.RoundedTextField();
        tfMunicipio = new test.RoundedTextField();
        tfInscricaoEstadual = new test.RoundedTextField();
        tfUF = new test.RoundedTextField();
        btnAdicionarTransp = new Components.btnRounded();
        btnRemoverTransp = new Components.btnRounded();
        btnAtualizarTransp = new Components.btnRounded();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1000, 596));
        setPreferredSize(new java.awt.Dimension(1000, 596));

        jPanel1.setBackground(new java.awt.Color(223, 223, 223));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cadastro de Transportadoras");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        tfRazaoSocialTransp.setBackground(new java.awt.Color(255, 255, 255));
        tfRazaoSocialTransp.setText("Aimê Uniformes e Cia Ltda");
        tfRazaoSocialTransp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfRazaoSocialTranspFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfRazaoSocialTranspFocusLost(evt);
            }
        });
        tfRazaoSocialTransp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRazaoSocialTranspActionPerformed(evt);
            }
        });

        tfCNPJ.setText("10.628.776/0001-04");
        tfCNPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCNPJFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCNPJFocusLost(evt);
            }
        });

        tfLogradouroTransp.setText("Rua Duque de Caxias");
        tfLogradouroTransp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfLogradouroTranspFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfLogradouroTranspFocusLost(evt);
            }
        });

        tfMunicipio.setText("Erechim");
        tfMunicipio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfMunicipioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfMunicipioFocusLost(evt);
            }
        });
        tfMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMunicipioActionPerformed(evt);
            }
        });

        tfInscricaoEstadual.setText("388.108.598.269");
        tfInscricaoEstadual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfInscricaoEstadualFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfInscricaoEstadualFocusLost(evt);
            }
        });

        tfUF.setText("RS");
        tfUF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUFFocusLost(evt);
            }
        });

        btnAdicionarTransp.setBackground(new java.awt.Color(0, 153, 153));
        btnAdicionarTransp.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionarTransp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/adicionarLogo.png"))); // NOI18N
        btnAdicionarTransp.setText("Adicionar");
        btnAdicionarTransp.setBorderColor(new java.awt.Color(0, 153, 153));
        btnAdicionarTransp.setColor(new java.awt.Color(0, 153, 153));
        btnAdicionarTransp.setColorClick(new java.awt.Color(0, 134, 134));
        btnAdicionarTransp.setColorOver(new java.awt.Color(0, 114, 114));

        btnRemoverTransp.setBackground(new java.awt.Color(153, 0, 0));
        btnRemoverTransp.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoverTransp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancelarLogo.png"))); // NOI18N
        btnRemoverTransp.setText("Remover");
        btnRemoverTransp.setBorderColor(new java.awt.Color(153, 0, 0));
        btnRemoverTransp.setColor(new java.awt.Color(153, 0, 0));
        btnRemoverTransp.setColorClick(new java.awt.Color(175, 0, 0));
        btnRemoverTransp.setColorOver(new java.awt.Color(154, 0, 0));

        btnAtualizarTransp.setBackground(new java.awt.Color(191, 189, 189));
        btnAtualizarTransp.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizarTransp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/atualizarLogo.png"))); // NOI18N
        btnAtualizarTransp.setText("Atualizar");
        btnAtualizarTransp.setBorderColor(new java.awt.Color(191, 189, 189));
        btnAtualizarTransp.setColor(new java.awt.Color(191, 189, 189));
        btnAtualizarTransp.setColorClick(new java.awt.Color(159, 159, 159));
        btnAtualizarTransp.setColorOver(new java.awt.Color(180, 180, 180));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Razão Social:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Logradouro:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Munucípio:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("CNPJ:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Inscrição Estadual:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("UF:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAtualizarTransp, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnRemoverTransp, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnAdicionarTransp, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfLogradouroTransp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfRazaoSocialTransp, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfInscricaoEstadual, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                                        .addComponent(tfUF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2)
                        .addGap(405, 405, 405)
                        .addComponent(jLabel5)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfRazaoSocialTransp, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(tfCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfInscricaoEstadual, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(tfLogradouroTransp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(tfUF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarTransp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoverTransp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizarTransp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfRazaoSocialTranspFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfRazaoSocialTranspFocusGained
        tfRazaoSocialTransp.setText("");
        tfRazaoSocialTransp.setForeground(Color.BLACK);
    }//GEN-LAST:event_tfRazaoSocialTranspFocusGained

    private void tfRazaoSocialTranspFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfRazaoSocialTranspFocusLost
        if (tfRazaoSocialTransp.getText().isEmpty()) {
            tfRazaoSocialTransp.setText("Aimê Uniformes e Cia Ltda");
            tfRazaoSocialTransp.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfRazaoSocialTranspFocusLost

    private void tfLogradouroTranspFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLogradouroTranspFocusGained
        tfLogradouroTransp.setText("");
        tfLogradouroTransp.setForeground(Color.BLACK);
    }//GEN-LAST:event_tfLogradouroTranspFocusGained

    private void tfLogradouroTranspFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLogradouroTranspFocusLost
        if(tfLogradouroTransp.getText().isEmpty()) {
            tfLogradouroTransp.setText("Rua Duque de Caxias");
            tfLogradouroTransp.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfLogradouroTranspFocusLost

    private void tfMunicipioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfMunicipioFocusGained
        tfMunicipio.setText("");
        tfMunicipio.setForeground(Color.BLACK);
    }//GEN-LAST:event_tfMunicipioFocusGained

    private void tfMunicipioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfMunicipioFocusLost
        if (tfMunicipio.getText().isEmpty()){
            tfMunicipio.setText("Erechim");
            tfMunicipio.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfMunicipioFocusLost

    private void tfCNPJFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCNPJFocusGained
        tfCNPJ.setText("");
        tfCNPJ.setForeground(Color.BLACK);
    }//GEN-LAST:event_tfCNPJFocusGained

    private void tfCNPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCNPJFocusLost
        if (tfCNPJ.getText().isEmpty()){
            tfCNPJ.setText("10.628.776/0001-04");
            tfCNPJ.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfCNPJFocusLost

    private void tfInscricaoEstadualFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfInscricaoEstadualFocusGained
        tfInscricaoEstadual.setText("");
        tfInscricaoEstadual.setForeground(Color.BLACK);
    }//GEN-LAST:event_tfInscricaoEstadualFocusGained

    private void tfInscricaoEstadualFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfInscricaoEstadualFocusLost
        if(tfInscricaoEstadual.getText().isEmpty()) {
            tfInscricaoEstadual.setText("388.108.598.269");
            tfInscricaoEstadual.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfInscricaoEstadualFocusLost

    private void tfUFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUFFocusGained
        tfUF.setText("");
        tfUF.setForeground(Color.BLACK);
    }//GEN-LAST:event_tfUFFocusGained

    private void tfUFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUFFocusLost
        if (tfUF.getText().isEmpty()) {
            tfUF.setText("RS");
            tfUF.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_tfUFFocusLost

    private void tfRazaoSocialTranspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRazaoSocialTranspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRazaoSocialTranspActionPerformed

    private void tfMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMunicipioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.btnRounded btnAdicionarTransp;
    private Components.btnRounded btnAtualizarTransp;
    private Components.btnRounded btnRemoverTransp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private test.RoundedTextField tfCNPJ;
    private test.RoundedTextField tfInscricaoEstadual;
    private test.RoundedTextField tfLogradouroTransp;
    private test.RoundedTextField tfMunicipio;
    private test.RoundedTextField tfRazaoSocialTransp;
    private test.RoundedTextField tfUF;
    // End of variables declaration//GEN-END:variables
}
